### ISSUE TITLE
unban me

### ISSUE THREAD

**Issue by him5** [LandonPowell/SeaFour#19]
can you unban me (here is some copy and pasting for proof): 
Type your message here.
Account Users - 0
Log In
Handle
 
Passphrase
 Log into SeaFour
Sign Up
Handle
 -
Passphrase
 
Confirm it
 Sign Up for SeaFour
Continue as a Guest

**Comment by mfroach** [comment]
No

**Comment by him5** [comment]
nevermind it was a socket error

**Comment by him5** [comment]
or something
