### ISSUE TITLE
Parser location

### ISSUE THREAD

**Issue by DoomsdayMuffinz** [LandonPowell/SeaFour#4]
The parser is located in client.js, which can be modified and then used to inject HTML. I've managed to inject anchors and iframes successfully on a local session by modifying the client.js.

**Comment by zgrep** [comment]
The only way I see this being an effective vector of attack is if you are sitting in the middle of the connection and inject a malicious client.js. But in that case why attack through the chat application, you're already sitting in the middle of the connection.

Personally, I don't see how this is a problem.

**Comment by LandonPowell** [comment]
Dooms, I love you fam, but you might be clinically retarded. Inspect element is not a vulnerability.
