### ISSUE TITLE
"listening on *:undefined"

### ISSUE THREAD

**Issue by DoomsdayMuffinz** [LandonPowell/SeaFour#5]
When starting server.js, it listens on a random port because of its use of environment variables.
i.e. `http.listen(process.env.PORT, function(){`. This means PORT must be declared when running server.js (`PORT=8080 node server.js`), otherwise a random port will be chosen.

**Comment by DoomsdayMuffinz** [comment]
Submitted a fix in my pull request.

**Comment by LandonPowell** [comment]
Thanks, dooms.

**Comment by DoomsdayMuffinz** [comment]
You're welcome ♡
